eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766
spring:
  application:
    name: zuul-server

zuul:
  routes:
    service-hello-world:
      path: /say/hello/**
      serviceId: service-hello-world
    gretting-service:
      path: /greeting/**
      serviceId: greeting-service