server:
  port: 8770

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://10.1.100.20:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
