server:
  port: 8762
spring:
  application:
    name: service-hello-world

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


hystrix:
  metrics:
    enabled: true # 开启降级
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

#  endpoint:
#    hystrix:
#      stream:
#        enabled: true

# feign默认不开启Hystrix
feign:
  hystrix:
    enabled: true
